version: "3.9"

services:
  backend:
    build: ./docvault
    container_name: docvault_backend
    ports:
      - "8000:8000"
    volumes:
      - ./docvault:/app
    environment:
      - DEBUG=1

  frontend:
    build: ./docvault-react
    container_name: docvault_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend