version: "3.9"

services:
  backend:
    build: ./docvault
    container_name: docvault_backend
    ports:
      - "8000:8000"
    volumes:
      - ./docvault:/app
    env_file:
      - .env

  frontend:
    build: ./docvault-react
    container_name: docvault_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./docvault-react:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend