# Generated by Django 6.0.3 on 2026-03-17 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='document',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='document',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='status',
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuve'), ('rejected', 'Refuse')], default='pending', max_length=10),
        ),
    ]
